name: call reusable build workflow

on:
 push:
  branches: [main]

jobs:
  call-reusable-build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app_name: "web-app"
      environment: "pre-production"
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}
  
  print-version:
    runs-on: ubuntu-latest
    needs: call-reusable-build
    steps:
      - name: Print build version
        run: |
          echo "Build version: ${{ needs.call-reusable-build.outputs.build_version }}"
