name: CICD

on:
   workflow_dispatch: 

jobs:


    code:
      runs-on: ubuntu-latest 
      steps:
        - name: checkout code
          run: echo "code clone from GitHub"
    build:
      runs-on: ubuntu-latest 
      steps:
        - name: build docker container
          run: echo "Docker Container build"
    test:
      runs-on: ubuntu-latest 
      steps: 
        - name: Test the container
          run: echo "Testing the container"
    deploy:
      runs-on: ubuntu-latest 
      steps: 
        - name: Deploying the app
          run: echo "Docker compose deployes the app"
    
