name: docker secrets-demo

on:
    workflow_dispatch:

jobs:
    secrets-demo:
        runs-on: ubuntu-latest
        steps: 
          - name: checkout repository
            uses: actions/checkout@v3

          - name: use Docker secrets
            env:
              DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
              DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
            run: |
              echo "Docker username: $DOCKER_USERNAME"
              echo "Logging into Docker"