name: Portfolio Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup Github Pages
        uses: actions/configure-pages@v4
    
      - name: upload static files
        uses: actions/upload-pages-artifact@v4
        
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4