name: Secrets Demo

on: push

jobs:
  secrets-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret exists
        run: |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The secret is set: true"
          else
            echo "The secret is NOT set"
          fi

      - name: Try printing secret (DO NOT DO THIS IN REAL)
        run: echo "${{ secrets.MY_SECRET_MESSAGE }}"